export const stageData = {
  1: {
    name: '벙커 외곽',
    description: '폐허가 된 도시의 변두리',
    theme: '돌연변이와 약탈자',
    combatPool: ['marauder1', 'marauder2', 'infectedDog'],
    miniboss: 'marauderLeader',
    boss: 'lumenReaper',
    eventPool: ['event_supplies', 'event_survivor', 'event_trap'],
    shopType: 'basic',
  },
  2: {
    name: '중립 지대',
    description: '빛을 먹은 식물과 이상 현상이 엉킨 구역',
    theme: '빛을 먹은 식물과 이상 현상',
    combatPool: ['shadowWraith', 'doppelganger', 'unpleasantCube'],
    miniboss: 'subject162',
    boss: 'chimera',
    eventPool: ['event_coin_pouch', 'event_wishing_well', 'event_supplies'],
    shopType: 'basic',
  },
  3: {
    name: '최종 심층',
    description: '외계 파동과 월식의 합창이 겹치는 마지막 관문',
    theme: '공명, 봉인, 저주가 폭발하는 심층 관문',
    combatPool: ['annihilationAmplifier', 'fleshCultivator', 'abyssObserver'],
    miniboss: 'apostleOfFlesh',
    boss: 'eclipseChoir',
    eventPool: ['event_stage3_resonance_relay', 'event_stage3_flesh_vat', 'event_stage3_eclipse_sanctuary'],
    shopType: 'basic',
  },
};
